//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cau1_lan3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV
    {
        public int manv { get; set; }
        public string tenvn { get; set; }
        public Nullable<int> hsluong { get; set; }
    }
}
